In [ ]:
# packages 
## libraries purposely built to provide solutions to a specific problem. 
# we have a lot of packages in phyton

# numpy - numerical phyton. it is used to perform mathematical operations

###  pandas - it is built to perform data manipulation

### matplot or seeborn or tlotly they are built to perform data visualization in [hyton]

### scikit or sklen - built to perform machine learning application

### keras or pytoch - this are built to perform deep learning application


In [ ]:
### using package, you need to install the package. 
###  package manager-  is used to install any package that you want to use -- pip

# pip install numpy

In [ ]:
# to import numpy
array is like a list, to store data

In [4]:
# creating one dimensional array from one dimension list
import numpy as np
list1 = [1,4,5,6,1,7]
arry1 = np.array(list1)
arry1


array([1, 4, 5, 6, 1, 7])

In [5]:
# checking the type of array
type(arry1)

numpy.ndarray

In [8]:
# creating two dimentional array from two dimensional list

list2 =  [[ 5,7,0,10,12,45 ]]
arry2 = np.array(list2)
arry2

array([[ 5,  7,  0, 10, 12, 45]])

In [9]:
# to check the dimension of array
arry2.ndim

2

In [13]:
# creating three dimentional array from one dimension list
list2 =  [[ 5,7,0,10,12,45 ]]
arry3 = np.array(list2,ndmin=3, dtype="complex")
arry3

array([[[ 5.+0.j,  7.+0.j,  0.+0.j, 10.+0.j, 12.+0.j, 45.+0.j]]])

In [18]:
# exercise
# create numpy array of three dimensions and integar data type from list below

list3 = [2,4,5,22,8,54,22]
arry3 = np.array(list3, ndmin=3, dtype="int")
arry3

array([[[ 2,  4,  5, 22,  8, 54, 22]]])

In [20]:
# Numpy - creating array from numerical ranges
# numpy.arrange(start, stop, skip, dtype)

np.arange(0,11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [23]:
# creating array using linspace
# numpy.linspace(start, stop, num, endpoint, dtype)

np.linspace(10,50,5, endpoint= True)

array([10., 20., 30., 40., 50.])

In [30]:
# create numpy array of object data type containing 8 element within 10 and 90. endpoint should be excluded

np.linspace(10,90,8, endpoint = False, dtype= "object")

array([10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0], dtype=object)

In [31]:
# create numpy of int data type from 7 to 70 with interval of 8 

np.arange(7, 71, 8, dtype= "int")

array([ 7, 15, 23, 31, 39, 47, 55, 63])

In [ ]:
# Attribute of array in numpy
##  1. shape- it will give the number of elements in each of the dimension.

In [33]:
# how to check the shape of the array

arry5 = np.array( [[[2,5],
          [8,3],
          [6,4]],
         
         [[1,6],
          [4,0],
          [4,5]]]) 
         
         
arry5.shape  

(2, 3, 2)

In [43]:
arry6 = np.arange(7,71,4, dtype = "int")
arry6

array([ 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67])

In [36]:
arry7= np.array([[ 2,6,7,8],
                 [2,6,7,8],
                 [2,6,7,8],
                 [2,6,7,8],
                 [2,6,5,7]])
    
    
arry7.shape
    


(5, 4)

In [38]:
# reshaping the shape of array **2 reshape()**
arry8 = np.arange(7,71,4, dtype = "int")
arry8.shape

(16,)

In [39]:
arry_reshape=arry8.reshape(4,4)
arry_reshape

array([[ 7, 11, 15, 19],
       [23, 27, 31, 35],
       [39, 43, 47, 51],
       [55, 59, 63, 67]])

In [41]:
arry_reshape=arry8.reshape(4,4)
arry_reshape.shape

(4, 4)

In [47]:
# indexing and slicing

arry10= [7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67]

arry10[2:14:3]




[15, 27, 39, 51]

In [48]:
# boolean indexing - is a way of fieltering out our data
# to fielter out all element less than 30
arry8[arry8> 30]

array([31, 35, 39, 43, 47, 51, 55, 59, 63, 67])

In [50]:
#np.flatten()  changing the dimension of array into one
## it is used to flatten the dimension from a bigger dimension to a smaller one

arry_reshape=arry8.reshape(16,1,1,1)
arry_reshape.shape

(16, 1, 1, 1)

In [53]:
arry_reshape.flatten().shape

array([ 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67])